import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

// 🧩 components
import Navbar from "@/components/Navbar";

// 🌿 context
import { SearchProvider } from "@/context/SearchProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`bg-secondary dark:bg-primary overflow-x-hidden overflow-y-scroll lg:overflow-y-hidden ${inter.className}`}
      >
        <SearchProvider>
          <Navbar />
          {children}
        </SearchProvider>
      </body>
    </html>
  );
}
